stages:
  - build

build:
  image: node:latest
  stage: build
  script:
    - npm install
    - npx electron-builder --linux AppImage deb
  artifacts:
    paths:
      - dist/*.AppImage
      - dist/*.deb
  only:
    - main

build_rpm:
  image: fedora:latest
  stage: build
  script:
    - dnf install nodejs npm rpmdevtools rpmlint libxcrypt-devel libxcrypt-compat -y
    - npm install
    - npx electron-builder --linux rpm
  artifacts:
    paths:
      - dist/*.rpm
