name: Node.js CI

on:
  push:
    branches: [ main, ci-testing ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    strategy:
      matrix:
        node-version: [18.12.1]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: echo GH_TOKEN=${{ secrets.GITHUB_TOKEN }} > .env
      - run: npm ci
      - run: npm run lint
      - run: npx electron-builder --windows msi
      - name: Upload Artifact
        uses: actions/upload-artifact@v3.2.1-node20
        with:
          name: NookSetup.msi
          if-no-files-found: error
          
